apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app-staging
  namespace: staging
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: my-app
        image: <docker-image>:<tag>
        ports:
        - containerPort: 3000
